### ISSUE TITLE
[Mod Conflict with Charm of Undying] Void Totem Fabric 1.19-2.0.0 doesn't work

### ISSUE THREAD

**Issue by typlosion14** [Affehund/VoidTotem#17] opened 2022-07-28 11:10 UTC
Hi,
I'm using the mods
voidtotem-fabric-1.19-2.0.0.jar
with Fabric 0.14.8
in the Modpack: https://www.curseforge.com/minecraft/modpacks/better-mc-fabric
config file: 
ADD_END_CITY_TREASURE = true
BLACKLISTED_DIMENSIONS = []
DISPLAY_TOTEM_ON_CHEST = true
GIVE_TOTEM_EFFECTS = false
IS_INVERTED_BLACKLIST = false
NEEDS_TOTEM = true
SHOW_TOTEM_TOOLTIP = false
TELEPORT_HEIGHT_OFFSET = 64
USE_TOTEM_FROM_INVENTORY = false
I record a video of how I try to use it : [https://youtu.be/GpE3_d_J7po](https://youtu.be/GpE3_d_J7po)
I don't know why but the mods just doesn't work how intended
Thanks for reading the issue

**Comment by Affehund** [comment] 2022-07-28 17:11
Hi, 
thank you for submitting this issue. 
I think the issue is a mod conflict with the [charm of undying](https://www.curseforge.com/minecraft/mc-mods/charm-of-undying-fabric) mod. Removing this mod, fixes the problem. I will contact the mod author to inform about this issue.

**Comment by typlosion14** [comment] 2022-07-28 18:49
After uninstalling charm of undying, the mod works, thanks!

**Comment by CamperSamu** [comment] 2022-07-28 19:27
This issue should stay open until https://github.com/illusivesoulworks/charmofundying/pull/12 is merged.

**Comment by CamperSamu** [comment] 2022-07-28 19:28
This issue should stay open until https://github.com/illusivesoulworks/charmofundying/pull/12 is merged.

**Comment by Affehund** [comment] 2022-07-28 20:40
Yes, it definitely should

**Comment by CamperSamu** [comment] 2022-07-29 15:21
This should be fixed now according to @TheIllusiveC4

**Closed as completed** 2022-07-29 19:05 UTC
Labels: bug
